// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _Activity // 0
    {
        _EyeLeftClosed = 0x0,
        _EyeRightClosed = 0x1,
        _MouthOpen = 0x2,
        _MouthMoved = 0x3,
        _LookingAway = 0x4,
        _Count = 0x5,
    }
}
