// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _Appearance // 0
    {
        _WearingGlasses = 0x0,
        _Count = 0x1,
    }
}
