// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _DetectionResult // 0
    {
        _Unknown = 0x0,
        _No = 0x1,
        _Maybe = 0x2,
        _Yes = 0x3,
    }
}
