// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _Expression // 0
    {
        _Neutral = 0x0,
        _Happy = 0x1,
        _Count = 0x2,
    }
}
