// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _FrameCapturedStatus // 0
    {
        _Unknown = 0x0,
        _Queued = 0x1,
        _Dropped = 0x2,
    }
}
