// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _HandType // 0
    {
        _NONE = 0x0,
        _LEFT = 0x1,
        _RIGHT = 0x2,
    }
}
