// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _HandState // 0
    {
        _Unknown = 0x0,
        _NotTracked = 0x1,
        _Open = 0x2,
        _Closed = 0x3,
        _Lasso = 0x4,
    }
}
