// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _JointType // 0
    {
        _SpineBase = 0x0,
        _SpineMid = 0x1,
        _Neck = 0x2,
        _Head = 0x3,
        _ShoulderLeft = 0x4,
        _ElbowLeft = 0x5,
        _WristLeft = 0x6,
        _HandLeft = 0x7,
        _ShoulderRight = 0x8,
        _ElbowRight = 0x9,
        _WristRight = 0xa,
        _HandRight = 0xb,
        _HipLeft = 0xc,
        _KneeLeft = 0xd,
        _AnkleLeft = 0xe,
        _FootLeft = 0xf,
        _HipRight = 0x10,
        _KneeRight = 0x11,
        _AnkleRight = 0x12,
        _FootRight = 0x13,
        _SpineShoulder = 0x14,
        _HandTipLeft = 0x15,
        _ThumbLeft = 0x16,
        _HandTipRight = 0x17,
        _ThumbRight = 0x18,
        _Count = 0x19,
    }
}
