// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectGestureSettings // 0
    {
        _None = 0x0,
        _Tap = 0x1,
        _ManipulationTranslateX = 0x40,
        _ManipulationTranslateY = 0x80,
        _ManipulationTranslateRailsX = 0x100,
        _ManipulationTranslateRailsY = 0x200,
        _ManipulationScale = 0x800,
        _ManipulationTranslateInertia = 0x1000,
        _KinectHold = 0x10000,
    }
}
