// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectEngagementMode // 0
    {
        _None = 0x0,
        _SystemOnePerson = 0x1,
        _SystemTwoPerson = 0x2,
        _ManualOnePerson = 0x3,
        _ManualTwoPerson = 0x4,
    }
}
