// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectAudioCalibrationState // 0
    {
        _Unknown = 0x0,
        _CalibrationRequired = 0x1,
        _Calibrated = 0x2,
    }
}
