// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectCapabilities // 0
    {
        _None = 0x0,
        _Vision = 0x1,
        _Audio = 0x2,
        _Face = 0x4,
        _Expressions = 0x8,
        _Gamechat = 0x10,
    }
}
