// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _TrackingState // 0
    {
        _NotTracked = 0x0,
        _Inferred = 0x1,
        _Tracked = 0x2,
    }
}
