// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IAudioBeamFrameArrivedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("e0dbe62d-2045-4571-8d1d-ecf3981e3c3d");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameReference(
            out IAudioBeamFrameReference audioBeamFrameReference
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameReferenceFunc==null) m_get_FrameReferenceFunc = (get_FrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameReferenceFunc));
            audioBeamFrameReference = new IAudioBeamFrameReference();
            return m_get_FrameReferenceFunc(m_ptr, out audioBeamFrameReference.PtrForNew);
        }
        delegate int get_FrameReferenceFunc(IntPtr self, out IntPtr audioBeamFrameReference);
        get_FrameReferenceFunc m_get_FrameReferenceFunc;

    }
}
