// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IBodyIndexFrameArrivedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("10b7e92e-b4f2-4a36-a459-06b2a4b249df");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameReference(
            out IBodyIndexFrameReference bodyIndexFrameReference
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameReferenceFunc==null) m_get_FrameReferenceFunc = (get_FrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameReferenceFunc));
            bodyIndexFrameReference = new IBodyIndexFrameReference();
            return m_get_FrameReferenceFunc(m_ptr, out bodyIndexFrameReference.PtrForNew);
        }
        delegate int get_FrameReferenceFunc(IntPtr self, out IntPtr bodyIndexFrameReference);
        get_FrameReferenceFunc m_get_FrameReferenceFunc;

    }
}
