// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IFrameCapturedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("24cbab8e-df1a-4fa8-827e-c1b27a44a3a1");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameType(
            out _FrameSourceTypes frameType
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameTypeFunc==null) m_get_FrameTypeFunc = (get_FrameTypeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameTypeFunc));
            
            return m_get_FrameTypeFunc(m_ptr, out frameType);
        }
        delegate int get_FrameTypeFunc(IntPtr self, out _FrameSourceTypes frameType);
        get_FrameTypeFunc m_get_FrameTypeFunc;

        public virtual int get_FrameStatus(
            out _FrameCapturedStatus frameStatus
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_FrameStatusFunc==null) m_get_FrameStatusFunc = (get_FrameStatusFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameStatusFunc));
            
            return m_get_FrameStatusFunc(m_ptr, out frameStatus);
        }
        delegate int get_FrameStatusFunc(IntPtr self, out _FrameCapturedStatus frameStatus);
        get_FrameStatusFunc m_get_FrameStatusFunc;

        public virtual int get_RelativeTime(
            out long relativeTime
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_RelativeTimeFunc==null) m_get_RelativeTimeFunc = (get_RelativeTimeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_RelativeTimeFunc));
            
            return m_get_RelativeTimeFunc(m_ptr, out relativeTime);
        }
        delegate int get_RelativeTimeFunc(IntPtr self, out long relativeTime);
        get_RelativeTimeFunc m_get_RelativeTimeFunc;

    }
}
