// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IIsAvailableChangedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("3a6dd52e-967f-4982-b3d9-74b9e1a044c9");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_IsAvailable(
            out byte isAvailable
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_IsAvailableFunc==null) m_get_IsAvailableFunc = (get_IsAvailableFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_IsAvailableFunc));
            
            return m_get_IsAvailableFunc(m_ptr, out isAvailable);
        }
        delegate int get_IsAvailableFunc(IntPtr self, out byte isAvailable);
        get_IsAvailableFunc m_get_IsAvailableFunc;

    }
}
