// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IKinectManipulationStartedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("2ec8a1ba-96ec-49f7-bd41-d5fe791f0d46");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_PointerDeviceType(
            out _PointerDeviceType value
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_PointerDeviceTypeFunc==null) m_get_PointerDeviceTypeFunc = (get_PointerDeviceTypeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PointerDeviceTypeFunc));
            
            return m_get_PointerDeviceTypeFunc(m_ptr, out value);
        }
        delegate int get_PointerDeviceTypeFunc(IntPtr self, out _PointerDeviceType value);
        get_PointerDeviceTypeFunc m_get_PointerDeviceTypeFunc;

        public virtual int get_Position(
            out _PointF value
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_PositionFunc==null) m_get_PositionFunc = (get_PositionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PositionFunc));
            
            return m_get_PositionFunc(m_ptr, out value);
        }
        delegate int get_PositionFunc(IntPtr self, out _PointF value);
        get_PositionFunc m_get_PositionFunc;

        public virtual int get_Cumulative(
            out _KinectManipulationDelta value
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_CumulativeFunc==null) m_get_CumulativeFunc = (get_CumulativeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_CumulativeFunc));
            
            return m_get_CumulativeFunc(m_ptr, out value);
        }
        delegate int get_CumulativeFunc(IntPtr self, out _KinectManipulationDelta value);
        get_CumulativeFunc m_get_CumulativeFunc;

    }
}
