// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IKinectManipulationCompletedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("98af1727-d511-459c-be14-16ca8230871b");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_PointerDeviceType(
            out _PointerDeviceType value
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_PointerDeviceTypeFunc==null) m_get_PointerDeviceTypeFunc = (get_PointerDeviceTypeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PointerDeviceTypeFunc));
            
            return m_get_PointerDeviceTypeFunc(m_ptr, out value);
        }
        delegate int get_PointerDeviceTypeFunc(IntPtr self, out _PointerDeviceType value);
        get_PointerDeviceTypeFunc m_get_PointerDeviceTypeFunc;

        public virtual int get_Position(
            out _PointF value
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_PositionFunc==null) m_get_PositionFunc = (get_PositionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PositionFunc));
            
            return m_get_PositionFunc(m_ptr, out value);
        }
        delegate int get_PositionFunc(IntPtr self, out _PointF value);
        get_PositionFunc m_get_PositionFunc;

        public virtual int get_Cumulative(
            out _KinectManipulationDelta value
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_CumulativeFunc==null) m_get_CumulativeFunc = (get_CumulativeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_CumulativeFunc));
            
            return m_get_CumulativeFunc(m_ptr, out value);
        }
        delegate int get_CumulativeFunc(IntPtr self, out _KinectManipulationDelta value);
        get_CumulativeFunc m_get_CumulativeFunc;

        public virtual int get_Velocities(
            out _KinectManipulationVelocities value
        ){
            var fp = GetFunctionPointer(6);
            if(m_get_VelocitiesFunc==null) m_get_VelocitiesFunc = (get_VelocitiesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_VelocitiesFunc));
            
            return m_get_VelocitiesFunc(m_ptr, out value);
        }
        delegate int get_VelocitiesFunc(IntPtr self, out _KinectManipulationVelocities value);
        get_VelocitiesFunc m_get_VelocitiesFunc;

    }
}
