// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IKinectPointerEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("65635ae1-3d28-4d5a-aa09-825aae07c1b1");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_Handled(
            out byte handled
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_HandledFunc==null) m_get_HandledFunc = (get_HandledFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_HandledFunc));
            
            return m_get_HandledFunc(m_ptr, out handled);
        }
        delegate int get_HandledFunc(IntPtr self, out byte handled);
        get_HandledFunc m_get_HandledFunc;

        public virtual int put_Handled(
            byte handled
        ){
            var fp = GetFunctionPointer(4);
            if(m_put_HandledFunc==null) m_put_HandledFunc = (put_HandledFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(put_HandledFunc));
            
            return m_put_HandledFunc(m_ptr, handled);
        }
        delegate int put_HandledFunc(IntPtr self, byte handled);
        put_HandledFunc m_put_HandledFunc;

        public virtual int get_CurrentPoint(
            out IKinectPointerPoint pointer
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_CurrentPointFunc==null) m_get_CurrentPointFunc = (get_CurrentPointFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_CurrentPointFunc));
            pointer = new IKinectPointerPoint();
            return m_get_CurrentPointFunc(m_ptr, out pointer.PtrForNew);
        }
        delegate int get_CurrentPointFunc(IntPtr self, out IntPtr pointer);
        get_CurrentPointFunc m_get_CurrentPointFunc;

    }
}
