// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IKinectPressingCompletedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("7b9dad43-0dfa-48dc-a2e3-cdba3b3e251f");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_Position(
            out _PointF value
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_PositionFunc==null) m_get_PositionFunc = (get_PositionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PositionFunc));
            
            return m_get_PositionFunc(m_ptr, out value);
        }
        delegate int get_PositionFunc(IntPtr self, out _PointF value);
        get_PositionFunc m_get_PositionFunc;

    }
}
