// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IMultiSourceFrameReference: IUnknown
    {
        static Guid s_uuid = new Guid("dd70e845-e283-4dd1-8daf-fc259ac5f9e3");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int AcquireFrame(
            out IMultiSourceFrame frame
        ){
            var fp = GetFunctionPointer(3);
            if(m_AcquireFrameFunc==null) m_AcquireFrameFunc = (AcquireFrameFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AcquireFrameFunc));
            frame = new IMultiSourceFrame();
            return m_AcquireFrameFunc(m_ptr, out frame.PtrForNew);
        }
        delegate int AcquireFrameFunc(IntPtr self, out IntPtr frame);
        AcquireFrameFunc m_AcquireFrameFunc;

    }
}
