// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    [StructLayout(LayoutKind.Sequential)]
    public struct _LARGE_INTEGER__anonymous_4 // 1
    {
        public uint LowPart;
        public int HighPart;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct _LARGE_INTEGER__anonymous_6 // 2
    {
        public uint LowPart;
        public int HighPart;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct _ULARGE_INTEGER__anonymous_10 // 1
    {
        public uint LowPart;
        public uint HighPart;
    }
    [StructLayout(LayoutKind.Sequential)]
    public struct _ULARGE_INTEGER__anonymous_11 // 2
    {
        public uint LowPart;
        public uint HighPart;
    }
    [StructLayout(LayoutKind.Explicit)]
    public struct _LARGE_INTEGER // 1
    {
        [FieldOffset(0)]
        public _LARGE_INTEGER__anonymous_4 __param__1;
        [FieldOffset(0)]
        public _LARGE_INTEGER__anonymous_6 __param__2;
        [FieldOffset(0)]
        public _LARGE_INTEGER__anonymous_6 u;
        [FieldOffset(0)]
        public long QuadPart;
    }
    [StructLayout(LayoutKind.Explicit)]
    public struct _ULARGE_INTEGER // 1
    {
        [FieldOffset(0)]
        public _ULARGE_INTEGER__anonymous_10 __param__1;
        [FieldOffset(0)]
        public _ULARGE_INTEGER__anonymous_11 __param__2;
        [FieldOffset(0)]
        public _ULARGE_INTEGER__anonymous_11 u;
        [FieldOffset(0)]
        public ulong QuadPart;
    }
}
