// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _AudioBeamMode // 0
    {
        _Automatic = 0x0,
        _Manual = 0x1,
    }
}
