// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _ColorImageFormat // 0
    {
        _None = 0x0,
        _Rgba = 0x1,
        _Yuv = 0x2,
        _Bgra = 0x3,
        _Bayer = 0x4,
        _Yuy2 = 0x5,
    }
}
