// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _FrameSourceTypes // 0
    {
        _None = 0x0,
        _Color = 0x1,
        _Infrared = 0x2,
        _LongExposureInfrared = 0x4,
        _Depth = 0x8,
        _BodyIndex = 0x10,
        _Body = 0x20,
        _Audio = 0x40,
    }
}
