// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _FrameEdges // 0
    {
        _None = 0x0,
        _Right = 0x1,
        _Left = 0x2,
        _Top = 0x4,
        _Bottom = 0x8,
    }
}
