// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectInteractionMode // 0
    {
        _Normal = 0x0,
        _Off = 0x1,
        _Media = 0x2,
    }
}
