// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _KinectHoldingState // 0
    {
        _Started = 0x0,
        _Completed = 0x1,
        _Canceled = 0x2,
    }
}
