// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _PointerDeviceType // 0
    {
        _Touch = 0x0,
        _Pen = 0x1,
        _Mouse = 0x2,
        _Kinect = 0x3,
    }
}
