// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public enum _TrackingConfidence // 0
    {
        _Low = 0x0,
        _High = 0x1,
    }
}
