// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IAudioBeamFrameReader: IUnknown
    {
        static Guid s_uuid = new Guid("b5733de9-6ecf-46b2-8b23-a16d71f1a75c");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int SubscribeFrameArrived(
            out long waitableHandle
        ){
            var fp = GetFunctionPointer(3);
            if(m_SubscribeFrameArrivedFunc==null) m_SubscribeFrameArrivedFunc = (SubscribeFrameArrivedFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(SubscribeFrameArrivedFunc));
            
            return m_SubscribeFrameArrivedFunc(m_ptr, out waitableHandle);
        }
        delegate int SubscribeFrameArrivedFunc(IntPtr self, out long waitableHandle);
        SubscribeFrameArrivedFunc m_SubscribeFrameArrivedFunc;

        public virtual int UnsubscribeFrameArrived(
            long waitableHandle
        ){
            var fp = GetFunctionPointer(4);
            if(m_UnsubscribeFrameArrivedFunc==null) m_UnsubscribeFrameArrivedFunc = (UnsubscribeFrameArrivedFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(UnsubscribeFrameArrivedFunc));
            
            return m_UnsubscribeFrameArrivedFunc(m_ptr, waitableHandle);
        }
        delegate int UnsubscribeFrameArrivedFunc(IntPtr self, long waitableHandle);
        UnsubscribeFrameArrivedFunc m_UnsubscribeFrameArrivedFunc;

        public virtual int GetFrameArrivedEventData(
            long waitableHandle,
            out IAudioBeamFrameArrivedEventArgs eventData
        ){
            var fp = GetFunctionPointer(5);
            if(m_GetFrameArrivedEventDataFunc==null) m_GetFrameArrivedEventDataFunc = (GetFrameArrivedEventDataFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(GetFrameArrivedEventDataFunc));
            eventData = new IAudioBeamFrameArrivedEventArgs();
            return m_GetFrameArrivedEventDataFunc(m_ptr, waitableHandle, out eventData.PtrForNew);
        }
        delegate int GetFrameArrivedEventDataFunc(IntPtr self, long waitableHandle, out IntPtr eventData);
        GetFrameArrivedEventDataFunc m_GetFrameArrivedEventDataFunc;

        public virtual int AcquireLatestBeamFrames(
            out IAudioBeamFrameList audioBeamFrameList
        ){
            var fp = GetFunctionPointer(6);
            if(m_AcquireLatestBeamFramesFunc==null) m_AcquireLatestBeamFramesFunc = (AcquireLatestBeamFramesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AcquireLatestBeamFramesFunc));
            audioBeamFrameList = new IAudioBeamFrameList();
            return m_AcquireLatestBeamFramesFunc(m_ptr, out audioBeamFrameList.PtrForNew);
        }
        delegate int AcquireLatestBeamFramesFunc(IntPtr self, out IntPtr audioBeamFrameList);
        AcquireLatestBeamFramesFunc m_AcquireLatestBeamFramesFunc;

        public virtual int get_IsPaused(
            out byte isPaused
        ){
            var fp = GetFunctionPointer(7);
            if(m_get_IsPausedFunc==null) m_get_IsPausedFunc = (get_IsPausedFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_IsPausedFunc));
            
            return m_get_IsPausedFunc(m_ptr, out isPaused);
        }
        delegate int get_IsPausedFunc(IntPtr self, out byte isPaused);
        get_IsPausedFunc m_get_IsPausedFunc;

        public virtual int put_IsPaused(
            byte isPaused
        ){
            var fp = GetFunctionPointer(8);
            if(m_put_IsPausedFunc==null) m_put_IsPausedFunc = (put_IsPausedFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(put_IsPausedFunc));
            
            return m_put_IsPausedFunc(m_ptr, isPaused);
        }
        delegate int put_IsPausedFunc(IntPtr self, byte isPaused);
        put_IsPausedFunc m_put_IsPausedFunc;

        public virtual int get_AudioSource(
            out IAudioSource audioSource
        ){
            var fp = GetFunctionPointer(9);
            if(m_get_AudioSourceFunc==null) m_get_AudioSourceFunc = (get_AudioSourceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_AudioSourceFunc));
            audioSource = new IAudioSource();
            return m_get_AudioSourceFunc(m_ptr, out audioSource.PtrForNew);
        }
        delegate int get_AudioSourceFunc(IntPtr self, out IntPtr audioSource);
        get_AudioSourceFunc m_get_AudioSourceFunc;

    }
}
