// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IAudioBeamFrameReference: IUnknown
    {
        static Guid s_uuid = new Guid("1bd29d0e-6304-4afb-9c85-77cfe3dc4fce");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int AcquireBeamFrames(
            out IAudioBeamFrameList audioBeamFrameList
        ){
            var fp = GetFunctionPointer(3);
            if(m_AcquireBeamFramesFunc==null) m_AcquireBeamFramesFunc = (AcquireBeamFramesFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(AcquireBeamFramesFunc));
            audioBeamFrameList = new IAudioBeamFrameList();
            return m_AcquireBeamFramesFunc(m_ptr, out audioBeamFrameList.PtrForNew);
        }
        delegate int AcquireBeamFramesFunc(IntPtr self, out IntPtr audioBeamFrameList);
        AcquireBeamFramesFunc m_AcquireBeamFramesFunc;

        public virtual int get_RelativeTime(
            out long relativeTime
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_RelativeTimeFunc==null) m_get_RelativeTimeFunc = (get_RelativeTimeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_RelativeTimeFunc));
            
            return m_get_RelativeTimeFunc(m_ptr, out relativeTime);
        }
        delegate int get_RelativeTimeFunc(IntPtr self, out long relativeTime);
        get_RelativeTimeFunc m_get_RelativeTimeFunc;

    }
}
