// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IAudioBodyCorrelation: IUnknown
    {
        static Guid s_uuid = new Guid("c5ba2355-07db-47c3-abc4-68d24b91de61");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_BodyTrackingId(
            out ulong trackingId
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_BodyTrackingIdFunc==null) m_get_BodyTrackingIdFunc = (get_BodyTrackingIdFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_BodyTrackingIdFunc));
            
            return m_get_BodyTrackingIdFunc(m_ptr, out trackingId);
        }
        delegate int get_BodyTrackingIdFunc(IntPtr self, out ulong trackingId);
        get_BodyTrackingIdFunc m_get_BodyTrackingIdFunc;

    }
}
