// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class ICoordinateMappingChangedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("e9a2a0bf-13bd-4a53-a157-91fc8bb41f85");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
    }
}
