// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IDepthFrameArrivedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("2b01bcb8-29d7-4726-860c-6da56664aa81");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameReference(
            out IDepthFrameReference depthFrameReference
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameReferenceFunc==null) m_get_FrameReferenceFunc = (get_FrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameReferenceFunc));
            depthFrameReference = new IDepthFrameReference();
            return m_get_FrameReferenceFunc(m_ptr, out depthFrameReference.PtrForNew);
        }
        delegate int get_FrameReferenceFunc(IntPtr self, out IntPtr depthFrameReference);
        get_FrameReferenceFunc m_get_FrameReferenceFunc;

    }
}
