// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IInfraredFrameArrivedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("7e17f78e-d9d1-4448-90c2-4e50ec4ecee9");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameReference(
            out IInfraredFrameReference infraredFrameReference
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameReferenceFunc==null) m_get_FrameReferenceFunc = (get_FrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameReferenceFunc));
            infraredFrameReference = new IInfraredFrameReference();
            return m_get_FrameReferenceFunc(m_ptr, out infraredFrameReference.PtrForNew);
        }
        delegate int get_FrameReferenceFunc(IntPtr self, out IntPtr infraredFrameReference);
        get_FrameReferenceFunc m_get_FrameReferenceFunc;

    }
}
