// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IKinectTappedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("c5b870c3-c819-4ff9-9f11-b5334d98761e");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_PointerDeviceType(
            out _PointerDeviceType value
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_PointerDeviceTypeFunc==null) m_get_PointerDeviceTypeFunc = (get_PointerDeviceTypeFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PointerDeviceTypeFunc));
            
            return m_get_PointerDeviceTypeFunc(m_ptr, out value);
        }
        delegate int get_PointerDeviceTypeFunc(IntPtr self, out _PointerDeviceType value);
        get_PointerDeviceTypeFunc m_get_PointerDeviceTypeFunc;

        public virtual int get_Position(
            out _PointF value
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_PositionFunc==null) m_get_PositionFunc = (get_PositionFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_PositionFunc));
            
            return m_get_PositionFunc(m_ptr, out value);
        }
        delegate int get_PositionFunc(IntPtr self, out _PointF value);
        get_PositionFunc m_get_PositionFunc;

        public virtual int get_TapCount(
            out uint value
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_TapCountFunc==null) m_get_TapCountFunc = (get_TapCountFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_TapCountFunc));
            
            return m_get_TapCountFunc(m_ptr, out value);
        }
        delegate int get_TapCountFunc(IntPtr self, out uint value);
        get_TapCountFunc m_get_TapCountFunc;

    }
}
