// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IMultiSourceFrameArrivedEventArgs: IUnknown
    {
        static Guid s_uuid = new Guid("3532f40b-d908-451d-bbf4-6ca73b782558");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_FrameReference(
            out IMultiSourceFrameReference frames
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_FrameReferenceFunc==null) m_get_FrameReferenceFunc = (get_FrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_FrameReferenceFunc));
            frames = new IMultiSourceFrameReference();
            return m_get_FrameReferenceFunc(m_ptr, out frames.PtrForNew);
        }
        delegate int get_FrameReferenceFunc(IntPtr self, out IntPtr frames);
        get_FrameReferenceFunc m_get_FrameReferenceFunc;

    }
}
