// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    public class IMultiSourceFrame: IUnknown
    {
        static Guid s_uuid = new Guid("29a63afb-76ce-4359-895a-997f1e094d1c");
        public static new ref Guid IID =>ref s_uuid;
        public override ref Guid GetIID(){ return ref s_uuid; }
                
        public virtual int get_ColorFrameReference(
            out IColorFrameReference colorFrameReference
        ){
            var fp = GetFunctionPointer(3);
            if(m_get_ColorFrameReferenceFunc==null) m_get_ColorFrameReferenceFunc = (get_ColorFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_ColorFrameReferenceFunc));
            colorFrameReference = new IColorFrameReference();
            return m_get_ColorFrameReferenceFunc(m_ptr, out colorFrameReference.PtrForNew);
        }
        delegate int get_ColorFrameReferenceFunc(IntPtr self, out IntPtr colorFrameReference);
        get_ColorFrameReferenceFunc m_get_ColorFrameReferenceFunc;

        public virtual int get_DepthFrameReference(
            out IDepthFrameReference depthFrameReference
        ){
            var fp = GetFunctionPointer(4);
            if(m_get_DepthFrameReferenceFunc==null) m_get_DepthFrameReferenceFunc = (get_DepthFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_DepthFrameReferenceFunc));
            depthFrameReference = new IDepthFrameReference();
            return m_get_DepthFrameReferenceFunc(m_ptr, out depthFrameReference.PtrForNew);
        }
        delegate int get_DepthFrameReferenceFunc(IntPtr self, out IntPtr depthFrameReference);
        get_DepthFrameReferenceFunc m_get_DepthFrameReferenceFunc;

        public virtual int get_BodyFrameReference(
            out IBodyFrameReference bodyFrameReference
        ){
            var fp = GetFunctionPointer(5);
            if(m_get_BodyFrameReferenceFunc==null) m_get_BodyFrameReferenceFunc = (get_BodyFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_BodyFrameReferenceFunc));
            bodyFrameReference = new IBodyFrameReference();
            return m_get_BodyFrameReferenceFunc(m_ptr, out bodyFrameReference.PtrForNew);
        }
        delegate int get_BodyFrameReferenceFunc(IntPtr self, out IntPtr bodyFrameReference);
        get_BodyFrameReferenceFunc m_get_BodyFrameReferenceFunc;

        public virtual int get_BodyIndexFrameReference(
            out IBodyIndexFrameReference bodyIndexFrameReference
        ){
            var fp = GetFunctionPointer(6);
            if(m_get_BodyIndexFrameReferenceFunc==null) m_get_BodyIndexFrameReferenceFunc = (get_BodyIndexFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_BodyIndexFrameReferenceFunc));
            bodyIndexFrameReference = new IBodyIndexFrameReference();
            return m_get_BodyIndexFrameReferenceFunc(m_ptr, out bodyIndexFrameReference.PtrForNew);
        }
        delegate int get_BodyIndexFrameReferenceFunc(IntPtr self, out IntPtr bodyIndexFrameReference);
        get_BodyIndexFrameReferenceFunc m_get_BodyIndexFrameReferenceFunc;

        public virtual int get_InfraredFrameReference(
            out IInfraredFrameReference infraredFrameReference
        ){
            var fp = GetFunctionPointer(7);
            if(m_get_InfraredFrameReferenceFunc==null) m_get_InfraredFrameReferenceFunc = (get_InfraredFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_InfraredFrameReferenceFunc));
            infraredFrameReference = new IInfraredFrameReference();
            return m_get_InfraredFrameReferenceFunc(m_ptr, out infraredFrameReference.PtrForNew);
        }
        delegate int get_InfraredFrameReferenceFunc(IntPtr self, out IntPtr infraredFrameReference);
        get_InfraredFrameReferenceFunc m_get_InfraredFrameReferenceFunc;

        public virtual int get_LongExposureInfraredFrameReference(
            out ILongExposureInfraredFrameReference longExposureInfraredFrameReference
        ){
            var fp = GetFunctionPointer(8);
            if(m_get_LongExposureInfraredFrameReferenceFunc==null) m_get_LongExposureInfraredFrameReferenceFunc = (get_LongExposureInfraredFrameReferenceFunc)Marshal.GetDelegateForFunctionPointer(fp, typeof(get_LongExposureInfraredFrameReferenceFunc));
            longExposureInfraredFrameReference = new ILongExposureInfraredFrameReference();
            return m_get_LongExposureInfraredFrameReferenceFunc(m_ptr, out longExposureInfraredFrameReference.PtrForNew);
        }
        delegate int get_LongExposureInfraredFrameReferenceFunc(IntPtr self, out IntPtr longExposureInfraredFrameReference);
        get_LongExposureInfraredFrameReferenceFunc m_get_LongExposureInfraredFrameReferenceFunc;

    }
}
