// This source code was generated by regenerator"
using System;
using System.Runtime.InteropServices;

namespace KinectSDK20 {
    [StructLayout(LayoutKind.Sequential)]
    public struct _FILETIME // 3
    {
        public uint dwLowDateTime;
        public uint dwHighDateTime;
    }
}
